name: condor
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - pip
  - pip:
      - python-telegram-bot[job-queue]
      - hummingbot-api-client
      - python-dotenv
      - pytest
      - pre-commit
      - black
      - isort
      - PyYAML
      - pydantic-ai
      - pydantic-ai-slim[openai]
